## Minisys TFT constraints for minisys_minecraft_tft_top
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

## Clock
set_property PACKAGE_PIN Y18 [get_ports clk_100m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100m]
create_clock -period 10.000 -name sys_clk [get_ports clk_100m]

## Buzzer
set_property PACKAGE_PIN A19 [get_ports buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]

## Buttons
set_property PACKAGE_PIN R1  [get_ports btn_up]
set_property PACKAGE_PIN P1  [get_ports btn_down]
set_property PACKAGE_PIN P5  [get_ports btn_left]
set_property PACKAGE_PIN P4  [get_ports btn_right]
set_property PACKAGE_PIN P2  [get_ports btn_action]
set_property PACKAGE_PIN P20 [get_ports btn_reset]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_reset btn_up btn_down btn_left btn_right btn_action}]

## Switches SW[23:0]
set_property PACKAGE_PIN Y9  [get_ports {sw[23]}]
set_property PACKAGE_PIN W9  [get_ports {sw[22]}]
set_property PACKAGE_PIN Y7  [get_ports {sw[21]}]
set_property PACKAGE_PIN Y8  [get_ports {sw[20]}]
set_property PACKAGE_PIN AB8 [get_ports {sw[19]}]
set_property PACKAGE_PIN AA8 [get_ports {sw[18]}]
set_property PACKAGE_PIN V8  [get_ports {sw[17]}]
set_property PACKAGE_PIN V9  [get_ports {sw[16]}]
set_property PACKAGE_PIN AB6 [get_ports {sw[15]}]
set_property PACKAGE_PIN AB7 [get_ports {sw[14]}]
set_property PACKAGE_PIN V7  [get_ports {sw[13]}]
set_property PACKAGE_PIN AA6 [get_ports {sw[12]}]
set_property PACKAGE_PIN Y6  [get_ports {sw[11]}]
set_property PACKAGE_PIN T6  [get_ports {sw[10]}]
set_property PACKAGE_PIN R6  [get_ports {sw[9]}]
set_property PACKAGE_PIN V5  [get_ports {sw[8]}]
set_property PACKAGE_PIN U6  [get_ports {sw[7]}]
set_property PACKAGE_PIN W5  [get_ports {sw[6]}]
set_property PACKAGE_PIN W6  [get_ports {sw[5]}]
set_property PACKAGE_PIN U5  [get_ports {sw[4]}]
set_property PACKAGE_PIN T5  [get_ports {sw[3]}]
set_property PACKAGE_PIN T4  [get_ports {sw[2]}]
set_property PACKAGE_PIN R4  [get_ports {sw[1]}]
set_property PACKAGE_PIN W4  [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

## LEDs
set_property PACKAGE_PIN K17 [get_ports {led_r[7]}]
set_property PACKAGE_PIN L13 [get_ports {led_r[6]}]
set_property PACKAGE_PIN M13 [get_ports {led_r[5]}]
set_property PACKAGE_PIN K14 [get_ports {led_r[4]}]
set_property PACKAGE_PIN K13 [get_ports {led_r[3]}]
set_property PACKAGE_PIN M20 [get_ports {led_r[2]}]
set_property PACKAGE_PIN N20 [get_ports {led_r[1]}]
set_property PACKAGE_PIN N19 [get_ports {led_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_r[*]}]

set_property PACKAGE_PIN F21 [get_ports {led_g[7]}]
set_property PACKAGE_PIN G22 [get_ports {led_g[6]}]
set_property PACKAGE_PIN G21 [get_ports {led_g[5]}]
set_property PACKAGE_PIN D21 [get_ports {led_g[4]}]
set_property PACKAGE_PIN E21 [get_ports {led_g[3]}]
set_property PACKAGE_PIN D22 [get_ports {led_g[2]}]
set_property PACKAGE_PIN E22 [get_ports {led_g[1]}]
set_property PACKAGE_PIN A21 [get_ports {led_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_g[*]}]

set_property PACKAGE_PIN M17 [get_ports {led_y[7]}]
set_property PACKAGE_PIN M16 [get_ports {led_y[6]}]
set_property PACKAGE_PIN M15 [get_ports {led_y[5]}]
set_property PACKAGE_PIN K16 [get_ports {led_y[4]}]
set_property PACKAGE_PIN L16 [get_ports {led_y[3]}]
set_property PACKAGE_PIN L15 [get_ports {led_y[2]}]
set_property PACKAGE_PIN L14 [get_ports {led_y[1]}]
set_property PACKAGE_PIN J17 [get_ports {led_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_y[*]}]

## Seven-segment display
set_property PACKAGE_PIN A18 [get_ports {seg_an[7]}]
set_property PACKAGE_PIN A20 [get_ports {seg_an[6]}]
set_property PACKAGE_PIN B20 [get_ports {seg_an[5]}]
set_property PACKAGE_PIN E18 [get_ports {seg_an[4]}]
set_property PACKAGE_PIN F18 [get_ports {seg_an[3]}]
set_property PACKAGE_PIN D19 [get_ports {seg_an[2]}]
set_property PACKAGE_PIN E19 [get_ports {seg_an[1]}]
set_property PACKAGE_PIN C19 [get_ports {seg_an[0]}]

set_property PACKAGE_PIN F15 [get_ports {seg_seg[0]}]
set_property PACKAGE_PIN F13 [get_ports {seg_seg[1]}]
set_property PACKAGE_PIN F14 [get_ports {seg_seg[2]}]
set_property PACKAGE_PIN F16 [get_ports {seg_seg[3]}]
set_property PACKAGE_PIN E17 [get_ports {seg_seg[4]}]
set_property PACKAGE_PIN C14 [get_ports {seg_seg[5]}]
set_property PACKAGE_PIN C15 [get_ports {seg_seg[6]}]
set_property PACKAGE_PIN E13 [get_ports {seg_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_an[*] seg_seg[*]}]

## TFT RGB output
set_property PACKAGE_PIN G17 [get_ports {TFT_R_O[0]}]
set_property PACKAGE_PIN G18 [get_ports {TFT_R_O[1]}]
set_property PACKAGE_PIN J15 [get_ports {TFT_R_O[2]}]
set_property PACKAGE_PIN H17 [get_ports {TFT_G_O[0]}]
set_property PACKAGE_PIN H18 [get_ports {TFT_G_O[1]}]
set_property PACKAGE_PIN H20 [get_ports {TFT_B_O[0]}]
set_property PACKAGE_PIN G20 [get_ports {TFT_B_O[1]}]
set_property PACKAGE_PIN K21 [get_ports {TFT_B_O[2]}]
set_property PACKAGE_PIN D20 [get_ports TFT_CLK_O]
set_property PACKAGE_PIN B16 [get_ports TFT_ADJ_O]
set_property PACKAGE_PIN C20 [get_ports TFT_DE_O]
set_property PACKAGE_PIN M21 [get_ports TFT_HSYNC_O]
set_property PACKAGE_PIN L21 [get_ports TFT_VSYNC_O]
set_property PACKAGE_PIN C18 [get_ports TFT_MODE_O]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_R_O[*] TFT_G_O[*] TFT_B_O[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_CLK_O TFT_ADJ_O TFT_DE_O TFT_HSYNC_O TFT_VSYNC_O TFT_MODE_O}]
